### ISSUE TITLE
Paranoia or actual fact?

### ISSUE THREAD

**Issue by naholyr** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#108]
Is the algorithm defining "top trending" developers and repos actually known with details? Is the infamous censorship actually provable or is it really paranoia *in fine*?

I think it's worth really thinking about this and gathering real proofs like opposing the algorithme and the numbers. This way you can say “it’s supposed to display us if we had more than X likes in the last Y hours, and we did, here are the proofs, so the only explanation is that someone (most supposedly MS) has manually removed us”.

Which is way more believable than "LOOK MA MS CENSORED US", which could definitely be true, but needs more facts.

**Comment by limonte** [comment]
> Is the infamous censorship actually provable or is it really paranoia in fine?

How can you prove or disprove something in the proprietary code?

**Comment by naholyr** [comment]
> How can you prove or disprove something in the proprietary code?

Then if you can't prove it, you should not claim it as a fact

**Comment by SayakMukhopadhyay** [comment]
This is scaremongering at its finest. MS doesn't need to do anything for people to not care about stupid stuff like this.

**Comment by limonte** [comment]
> Then if you can't prove it, you should not claim it as a fact

Kinda agree with you. But the inability to prove something doesn't mean we can't make **assumptions**, right? I'm not the native English speaker and the statement in the readme seems OK to me, but if other people see "100% proved fact" in that sentence, then the sentence should be changed.

**Comment by vassudanagunta** [comment]
The idea that this is some anti-spam mechanism is farcical. Getting 4000 stars is not something you can just fake. There is no army of Russian bots creating GitHub accounts and staring the repo. You are free to click on the stargazers and review their histories. 

Occam's razor: Deliberate removal. 

> Then if you can't prove it, you should not claim it as a fact

This is not a newspaper. UpEnd is making a charge. 

They've neither shown us the code or answered my charge. So the charge will stand.

UpEnd's position is that GitHub has not been honest with it's users, because it built its business on an implied promise to open source developers that they were a neutral corporation with no conflict of interest, then built it up enough to sell to a non-neutral corporation with immense conflict of interest for $7,500,000,000.

**Comment by SayakMukhopadhyay** [comment]
Great! So, anybody who doesn't share your conspiratorial point of view ends up being called a troll and have their issue (point of view) closed. Look, Github is not the only fish out there. If you are paranoid about the future of Github, you are free to look for other services.

**Comment by vassudanagunta** [comment]
I'll be making a change to this repo tomorrow, because: 

1. Not everyone agrees with me or the purpose of this repo.
2. This repo was never a public forum, but too many people are treating it as one. 
3. This repo can't be a community effort, because we have no consensus community here.

I will ask people to self organize into whatever groups they want wherever they want, and I can link to their efforts from this repo. More later.

**Comment by naholyr** [comment]
UPEND CENSORED MY COMMENT

**Comment by rdebath** [comment]
@vassudanagunta You are in Eastern Europe your timezone is close to UTC (like mine).  Github's offices are in America they are mostly asleep and not at work right now. An anti spam rule as to be dumb, it has to fail on the "oops I'm sorry I'll put that back" side rather than the "Oh dear a hate group got on our homepage" side.

Your headline is fine right now; but be prepared to change it when they get into the office.

**Comment by vassudanagunta** [comment]
I am in New York. We have been off the list for nearly 24 hours. So that cannot be the reason.

**Comment by rdebath** [comment]
Ah, sorry, I should have realised you wouldn't have any problem touching this repo at 4am. :smile:

**Comment by dispix** [comment]
> This repo can't be a community effort, because we have no consensus community here.

I think this is a critical point that should be expressed in the README. I guess a lot of people came here precisely to create a community important enough to have an impact on how Github handles this event. The fact that you are now expressing quite the opposite and closing issues/deleting comments left and right, while screaming "CENSORSHIP" when Github supposedly removes this repo from the top trend, has the potential to hurt the credibility of the whole initiative.

**Comment by vassudanagunta** [comment]
@dispix,

First, it is not a contradiction. Read my comments at the top of #91.  This is not a public forum and never was! But GitHub claims to be an open non-desciminating platform, and the trends page implies truth. 

> to create a community

>  to have an impact on how Github handles this event. 

It isn't as easy as you think to do the first in a way that makes everyone happy and do the second. They are almost contradictory goals. 

Have you ever tried to create a community? Or led one? Have you ever run a startup, or run a multi-million dollar project in a large company? If you have, you would know that getting shit done and "open ended community that welcomes all people of all opinions and philosophies" is a fools errand. All you have to do is look at any successful open source project and you will see this truth there too. They are all run by a (benevolent) dictator, or a team of people who knew they had like minds before teaming up. Do you think, for example, that the Jekyll project would tolerate people coming in and opening issues rudely mocking their choice of Ruby? 

It was my mistake not to forget this during the rush to respond to the acquisition. 

Anyway, I will correct this problem tomorrow. I need some sleep now.
