### ISSUE TITLE
The readme needs to articulate why

### ISSUE THREAD

**Issue by differentsmoke** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#13]
The readme needs an articulate, explicit description of your point, why you think it is bad, what the problems will be, etc. So far, it just seems like an aversion to Microsoft, which ultimately I don't believe is your main point.

**Comment by emmekappa** [comment]
So it's ok for GitHub Company to _concentrate the power_ but not for Microsoft Corp. ?

**Comment by vassudanagunta** [comment]
You may be right, that a solution that is entirely decentralized would be better for open source. Many people believe that. But there is also an argument that any community needs a shared town square, a community hall, a place to gather and see what everyone else is up to. If so, such a place needs to be independent. Such a place should only have one agenda: to host and service this community. Maybe relying on a for-profit company such as GitHub to be that steward isn't ideal, but at least if it's profit was dependent entirely on doing this right, it could work, even if imperfectly. 

GitHub's concentration of power was organic, created by and existing for the open source ecosystem. 

Microsoft does not exist for the open source community. It has its own agenda. For it, this is just a play. A chess move. we are the pawns. Acquisitions are not an organic growths in power. They are about domination. For example, [American tech giants are making life tough for startups](https://www.economist.com/business/2018/06/02/american-tech-giants-are-making-life-tough-for-startups).

I'm curious why you are eager to defend a $750 billion company and distrust the instincts of people who believe in open source, in doing things for the world not-for-profit but just to do things for the world, who believe in independence, who instinctively distrust concentration of power, _especially_ inorganic ones like this.

**Comment by prestonvanloon** [comment]
@vassudanagunta, I still think your motivation is an aversion to Microsoft, after reading you comments.

Microsoft is one of the biggest contributors to open source community. They have created over 7000 open source projects including VS Code, Typescript, and RxJS. Microsoft also has the infrastructure and resources to scale and grow GitHub.

I’m not defending the Microsoft, but I don’t see why this acquisition is bad. Why should anyone exert any amount of energy by being upset, moving off GitHub or creating repos like this one?

If/when GitHub starts to turn to shit, then I’ll leave. Otherwise who cares? Microsoft might make this a better place and you haven’t even given them a chance.

**Comment by immexerxez** [comment]
I don't think most of you are really understanding why this is a problem. There is a huge conflict of interest with Microsoft owning Github vs Github owning itself. Microsoft is a **software** company Github is a **hosting** company. Microsoft has huge incentives to take Github and not only push their own products but push traffic away from their competitors or in the extreme push them off the site. With Github being owned by itself it actually has gigantic incentives to **NOT** do this.

**Comment by ihavenonickname** [comment]
They won't elaborate because there is no way to elaborate this BS. The readme is simply a rant of a childish wannabe-revolutionary teenager.

**Comment by differentsmoke** [comment]
That is, indeed, a potential conflict of interests but, is there an actual incentive for Microsoft to do this? 
1. They have gotten in trouble in the past (for practices that Apple currently engages in without much resistance, btw).
2. The FLOSS community has punished misbehaving platforms in the past to a large degree of effectiveness (remember Sourceforge?).
3. Microsoft (like Google and Amazon) is moving towards SaaS/PaaS,and infrastructure business, and it is in their best interest to foster all software development.

**Comment by skonnor147** [comment]
You people are funny.

How many of you know that Microsoft owns LinkedIn? https://en.wikipedia.org/wiki/LinkedIn

This makes me wonder how many of you have been forced to work for Microsoft by them exploiting their power over online services such as this?

None? Yes that’s right, I think none. 

Microsoft are one of the largest contributors to the Linux kernel and open source software and your fear of this company is irrational. You massive bunch of fools!

Change is inevitable, deal with it and stop throwing your toys out of the pram.

**Comment by immexerxez** [comment]
What draws people to Github is/was the belief that they're impartial and it's 100% in their interest to remain as impartial as they possibly can. Github has become more than just open source software it's become the place to share all sorts of information a great example I'd say is how the Chinese community has developed even though they'd be censored in their own county. Microsoft fundamentally will never have this level of impartiality because in no circumstance would that make sense in their primary business. They could very well operate Github completely impartially but there will always be some form of mistrust within the user base because at the end of the day they are a business that needs to make money w/ competitors.

**Comment by vassudanagunta** [comment]
I'm not going to tolerate rudeness or trolling here. This is not a forum for debate. This is a space for GitHub Refugees. Please respect us and take your arguments elsewhere.

**Comment by bderiso** [comment]
+1 to this issue. Popularity does NOT mean you have a good point, only that it’s fun to bash Microsoft sometimes.

**Comment by emmekappa** [comment]
the conference call is live right now https://edge.media-server.com/m6/p/eudfciq3/dmediaset/audio

**Comment by bderiso** [comment]
And frankly your (possibly unintentional) straw man treatment of the 1st commenter and subsequent attempt to squash debate turn this into more of a reddit thread instead of anything useful.

**Comment by immexerxez** [comment]
I think it does more harm than good to delete comments. All opinions here are valid.

**Comment by vassudanagunta** [comment]
@immexerxez yes, all opinions are valid. But this is not a forum for debate. This is a place for people who wanted an independent GitHub, and will leave if it isn't. You don't go into some Node project's repo, for example, and start making comments on issues arguing that they should switch to Ruby.

**Comment by immexerxez** [comment]
@differentsmoke they already did pull a fast one on VS Code users after the update I believe last month (anyone feel free to correct that) they automatically set 

'''js
    "telemetry.enableCrashReporter": true,
    "telemetry.enableTelemetry": true
'''
did not warn users and expected you to find/disable. 

As for 5. that is really interesting and I'd love to hear some peoples take on it. In that sense it really feels like stuck between a rock and a hard place and honestly if it came to it I'd rather them be acquired even by microsoft than have to fend for themselves w/ shareholders to appease every quarter.

**Comment by GitSquared** [comment]
If i may add my two cents to this comment section:

As @vassudanagunta stated in another comment, the problem with MSFT acquiring GitHub is mainly about the concentration of power.

I'm sure Microsoft can do great things with GitHub. Satya Nadella (MSFT's CEO) has some history of willing to open up the company's massive codebase and promote open-source projects. But he's just a temporary commander of a massive organization that could abuse the enormous control they have over what we as developers do online.

Just think about it : **Microsoft now owns** (or at least will in a couple of months) **both GitHub and LinkedIn**. That's the services most recruiters use to find developers (particularly freelance).

I don't know how this will turn out but if you really believe in the whole open-source spirit and concept, you *should* move out just for the sake of staying away from the GAFAMs.

**Comment by quantumpacket** [comment]
https://jacquesmattheij.com/what-is-wrong-with-microsoft-buying-github

**Comment by cooldesigns** [comment]
Also you must add to readme like that "Join discussions on issues"

**Comment by vassudanagunta** [comment]
I cleaned up the README considerably. The opening expresses the gist of why without diving into an essay. I think that is sufficient for now. The purpose of this repo is not to debate whether the acquisition is good or bad... it's for people who already think it's bad who want to know what to do next. Any debate should be on that latter point.

**Comment by cooldesigns** [comment]
@vassudanagunta I'm talking about the debate about what the solution will be. For those who think the sale is bad.

**Comment by komali2** [comment]
@vassudanagunta your first reply is Argumentum ad populum and is a [logical fallacy](https://en.wikipedia.org/wiki/Argumentum_ad_populum)

100,000,000 Americans believing it intelligent design doesn't add any weight to the intelligent design argument.

**Comment by komali2** [comment]
@immexerxez  point that the existence of a single incentive outweighs all other incentives. 

The listed incentives to make github bad are

1. because microsoft could push out all other competitors 

The listed incentives to make github not-bad are

1. any malpractice by microsoft will erode years of open-source evangelizing in an microsecond

2. Everyone is watching and they will not get away with it

3. making github bad will push people to other platforms and reduce microsoft developer audience 

Given that if they do incentive 1 for make-github-bad, the very existence of incentive 3 (other people can just go to other platforms) makes this argument perfectly untenable. The reason is they will be exchanging a tiny amount of platform control / profit for an incalculable amount of bad press, and that platform control will then immediately vanish. 

This is like speculating that Oscar Meyer might publicly use dog meat in their hot dogs to save a buck. It doesn't make sense in the context (a planet with internet access and the means to tell eachother that oscar meyer is making hot dogs out of dog meat).

**Comment by vassudanagunta** [comment]
Hey guys. I love the work you've been doing. Not everyone loves mine. Please read Issue 114.

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas

**Comment by vassudanagunta** [comment]
> ## The readme needs to articulate why
> The readme needs an articulate, explicit description of your point, why you think it is bad, what the problems will be, etc. So far, it just seems like an aversion to Microsoft, which ultimately I don't believe is your main point.

Done: https://gitlab.com/upend/upend.org-content/blob/master/raison-d-etre.md
