### ISSUE TITLE
Sending the right message

### ISSUE THREAD

**Issue by immexerxez** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#24]
At first when I heard the news I was devastated and figured this would be the end of the Github I know and love but in all reality it isn't **yet**. Github's strength was never that it was free or that it was the big dog in open source. It was because everyone came here Huge corporations **and** regular people  contributed, and it remained/appeared to be impartial. In my earlier comments on a different issue I said Microsoft can't be trusted and we inevitably will lose but that is the **wrong** attitude. **We aren't refugees**. You can't just flee when you don't like something and we don't even know yet what the outcome will be. It's really easy to throw your hands up and run away. Everyone should stay, make their voices heard and if that doesn't work and Microsoft does ruin Github, leave.

**Comment by vassudanagunta** [comment]
You are not a refugee. But I am. 

From the outset I made this about GitHub and it's *independence*. I *never* made this about Microsoft, regardless of my opinion of them. 

This is the phrase on the upend GitHub organization page: `Upend the web oligarchy. #resist`

This is the text on the upend.org homepage:

```
upend.org

a future rebel base of the web resistance.

take back the web. take back our world.

#resist
```

And on Twitter, through which I've been driving a lot of traffic to this repo (and getting little sleep), I've made the message very clear. 

*This is about principles. It's about the open source ethos. It's about the need for independence **especially** for something like the home of the open source community. This is about resisting the concentration of power, as well as money being the arbiter of everything.*

I can go on, and I will as I develop upend.org.

So, for people like me, this was my home, and it was just taken over by coup-de-tat. It is no longer my home because of that. So I am a refugee. 

> You can't just flee when you don't like something and we don't even know yet what the outcome will be. 

That's like telling someone after some big country has taken over your little one: *You can't just flee. We don't even know yet the outcome. Maybe they they will be good rulers*. 

You're opinion is perfectly valid. But movements have to have some coherency of vision. A vision some one or some few present. And people join based on whether they align with that vision. I'm sorry if you got this one wrong. Maybe this isn't the place for you. I mean that quite genuinely and with all the best intent. Follow your heart. ❤️

**Comment by bashrc** [comment]
I'm not going to beg Microsoft for anything.

The only question I'm having right now is whether to close my account now or give it a few days. If you take a look at my profile you'll notice that my activity on Githib over the last five years has not exactly been trivial. But for me Microsoft is a red line. I had no objection to them being a user on Github like many others, but them being an intermediary between me and my repos ain't gonna happen.

**Comment by vassudanagunta** [comment]
Hey all. I love the work you've been doing. Not everyone loves mine. Please read Issue 114.

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas
