### ISSUE TITLE
Tone Down the Rhetoric

### ISSUE THREAD

**Issue by sethpuckett** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#26]
I understand that some folks are not happy about the acquisition, but the sincere "refugee camp" language in this repo is a bit much. Developers looking for a new repo platform is very different than families being ripped apart and struggling to survive in war-torn countries. It's a little offensive, to be honest.

Maybe update the `readme` to refer to supporters as "defectors" (or something similar) instead of "refugees"? And maybe tone down some of the conflict zone rhetoric ("resistance movement", "escape routes")?

**Comment by immexerxez** [comment]
I agree this repo's gone a little extreme I can't agree with the idea of using certain words somehow delegitimizes someones struggle. It's this sort of thinking is off topic and in a lot of ways dangerous.

**Comment by bashrc** [comment]
I also agree, although elsewhere people moving out of silos onto the open web are usually called "$systemname refugees".

Also people are passionate about their projects, and they don't like it when the space they inhabited is being colonized by corporate schmucks with a solid history of antisocial and disruptive behavior against FOSS developers.

**Comment by vassudanagunta** [comment]
@sethpuckett perhaps you are right.

[See my reply](https://github.com/upend/IF_MS_BUYS_GITHUB_IMMA_OUT/issues/24#issuecomment-394424060) to @immexerxez to understand why I chose those words, even if you are right that it would be better to change them. 

But #resist and #resistance are well establish terms of fighting "the power",  There's a reason this org is named [upend.org](http://www.upend.org). 

So, no, I'm not going to tone it down, because I think it's appropriately toned up for the perspective and spirit of this organization and future website. But yes, if it actually is offensive to refugees, I/we should change those words. Though I'd like to hear from an actual refugee. They might disagree with you. They might think that the metaphor is appropriate and appropriately powerful. I'm willing to listen.

At some point, I don't want this to be me running this thing. I'd rather have a team of people making collective decisions. But that team needs to have a shared vision. This isn't up for vote from people with entirely different visions, the extreme case being a GitHub or Microsoft employee coming in here and steering it their way.

And I'm sorry if you misunderstood the spirit of this effort. Follow your heart.

**Comment by vassudanagunta** [comment]
@bashrc 

> I also agree, although elsewhere people moving out of silos onto the open web are usually called "$systemname refugees".

I used refugee because this is the second time I've been part of a community that got destroyed by a takeover, and we called ourselves the "Newsvine Refugees". Funny, only now that you make me thinkg about it, that was a take-over of a citizenship journalism startup that we users poured our blood and sweat into for no pay, and then the founder just sold out to MSNBC for millions and destroyed everything we worked for.

**Comment by willyhakim** [comment]
Ok, as a kid who grew up in the refugee camp, I honestly was disgusted by this. I mean, have you seen pictures of Syrian Refugees? Com'on man! The day you go for 5 days without a meal because of this acquisition, you'll have my support to call this thing a refugee camp. For now, let's respect the people who are dying everyday in the literal refugee camps

**Comment by immexerxez** [comment]
This is off topic and is actually counterintuitive to the entire point of this repo.

**Comment by themusicgod1** [comment]
1) I have gone 5+ consecutive days without a meal for some of the projects on github.  Now Microsoft has effective control of those projects, and renders my sacrifices moot.  These projects represent the life's work of many people and extreme language is warranted for their sacrifices being made in vain.

2) 'refugee' has established meaning beyond refugee camps that does cover this kind of use

**Comment by sirjessthebrave** [comment]
Tech does not exist in a vacuum and words matter.... ESPECIALLY in our current political climate.  There are plenty of ways to express anger, frustration, and anti-capitalism without using the language of refugees and their unique, dire struggle.  

Some good documentation for better language: 
http://www.thesaurus.com/
https://blog.thejuntoinstitute.com/hs-fs/hubfs/social-suggested-images/The_Junto_Institute_Emotion_Wheel.jpeg?t=1527792324096&width=400&name=The_Junto_Institute_Emotion_Wheel.jpeg

**Comment by immexerxez** [comment]
this is way out off topic and should be closed. The entire point of this repo was to promote a free and open Github. Free and open includes language **some** might deem **offensive**.

**Comment by vassudanagunta** [comment]
Ok, message heard loud and clear. I'm sorry. didn't mean to offend. I'm on it. Though I haven't slept in 38 hours.

**Comment by vassudanagunta** [comment]
I'd love it if someone can suggest a rewrite that maintains the spirit of resistance. Again see [my reply](https://github.com/upend/IF_MS_BUYS_GITHUB_IMMA_OUT/issues/24#issuecomment-394424060) to @immexerxez.  

Pull request yo!

**Comment by vassudanagunta** [comment]
> this is way out off topic and should be closed. The entire point of this repo was to promote a free and open Github. Free and open includes language some might deem offensive.

Free and open also means allowing people to be led by heir hearts, not their wallets. Free and open is about humanity. Free and open to form a community with a culture of your choosing. I choose love and empathy over attitudes of entitlement.

**Comment by sirjessthebrave** [comment]
> Free and open is about humanity.
Humanity is about recognizing the lager context including language ect.

@vassudanagunta My ideas for better words include: renegade, outlaw, deserter, rebel

all have connotations of rebellion, resistance, and free, open communities somewhat outside the norm(capitalism)

**Comment by immexerxez** [comment]
this is not an anti-capitalism repo? This has nothing to do with economic systems? This is not on topic and is way off in the weeds.

**Comment by sirjessthebrave** [comment]
Bro we get it - you don't agree.... 

@vassudanagunta  has mentioned being free of corporate control hence capitalism comments. It takes very little effort to update language if it offends people. It is on topic for those on the thread so deal with it.

**Comment by vassudanagunta** [comment]
@immexerxez i'm getting the since we're on different wavelengths. If you don't align much with that long answer I gave you on the other thread (linked above a couple of times), then, frankly, I don't think you fit. I'm not going to change the spirit of this. It was there from the get-go. Maybe you starred without looking.

**Comment by sirjessthebrave** [comment]
@vassudanagunta Proposed PR: https://github.com/upend/IF_MS_BUYS_GITHUB_IMMA_OUT/pull/35

If you find a better word than outlaw you can always update it but for now it allows anger without offense.

**Comment by vassudanagunta** [comment]
OK folks, I changed the wording. "Evacuation Center" and "evacuees".  That ok?

@sirjessthebrave thank you, but we're the good guys.

**Comment by sethpuckett** [comment]
Thanks for updating the wording, @vassudanagunta!

**Comment by vassudanagunta** [comment]
@sethpuckett @willyhakim Thanks for calling this out. If you knew me, you would know this innocent. I call out others on this kind of stuff all the time, but in this case I simply did not make the connection (hence I did not offend myself).
