### ISSUE TITLE
GitHub was never free and it's a big company just like Microsoft

### ISSUE THREAD

**Issue by greenboxal** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#5]
Get over it

**Comment by YgorCastor** [comment]
Off course it was! Just like facebook is! Ohh, no w8.

**Comment by bamorim** [comment]
Well, if they are so amazing why they are selling it to Microsoft?

**Comment by damm** [comment]
That's a good conversation because knowing how github started without VC and no debt; I imagine bad management and infrastructure cost haunt them.

They give you/us free space and you don't pay for anything with a free account; just a bunch of repos.  Is there advertising to help bring in revenue? right 

Don't be shocked when you start seeing banners inbetween diff's in a PR request.

**Comment by AlexSwensen** [comment]
@vassudanagunta The fact that you close all issues that disagree with your point of view shows that you are not the right person to lead this movement. You are closed to any ideas that disagree with your own.

**Comment by vassudanagunta** [comment]
On the question of censorship, please read Issue 114.

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas
