### ISSUE TITLE
GitCenter - A Decentralized Git Repository Platform

### ISSUE THREAD

**Issue by ferittuncer** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#72]
I was thinking about a solution powered by [ZeroNet](https://zeronet.io/) then @krixano pointed out on #44  that there is already one: [GitCenter](https://github.com/imachug/gitcenter)

It is decentralized, every client is also a server, like BitTorrent. So there is no hosting cost and application is available as long as one peer is online. This also makes it censorship resistant because there is no centralized server to block.

In addition, this is a platform like GitHub, not like a self-hosted git server. So people can browse others' repositories.

I just tried it myself, seems like works well. It is developed by @imachug who is also [very active in ZeroNet development](https://github.com/HelloZeroNet/ZeroNet/graphs/contributors).

------

**Steps to start using it:**

1. Install [ZeroNet](https://zeronet.io/)
2. Go to http://127.0.0.1:43110/gitcenter.bit

-----
[ZeroNet Presentation](https://docs.google.com/presentation/d/1_2qK1IuOKJ51pgBvllZ9Yu7Au2l551t3XBgyTSvilew/pub?start=false&loop=false&delayms=3000#slide=id.g9a1cce9ee_0_9)

**Comment by krixano** [comment]
I've also created a post about how to migrate using git cli on ZeroTalk (Don't have the link right now).

**Comment by ozanonurtek** [comment]
It sounds good actually but the horrible part is, if no peer = no git. :rofl:

**Comment by ferittuncer** [comment]
If no peer, no Bitcoin also, how about that? :D Yet it works like a charm.

Another example: Even if GitHub is centralized if they wouldn't have any user they would shut it down, why would they keep it up?

No peer scenario is not a serious concern. As long as it is valuable to the community, there will be peers.

**Comment by cooldesigns** [comment]
We can't browse the zeronet on the www. It has no index repos on google. It is hosts own code on github. comic

It have to make a tunnel to www.

**Comment by krixano** [comment]
> It sounds good actually but the horrible part is, if no peer = no git. 🤣

This isn't exactly true, but I really don't want to get into that right now. Maybe I will later.

> We can't browse the zeronet on the www. It has no index repos on google. It is hosts own code on github. comic

You're wanting a proxy. There are some ZeroNet proxies - search for them.

Of course it hosts stuff on GitHub, because that was the number one place to get repos, etc. It was literally only *just* announced that Microsoft bought GitHub - give @HelloZeroNet some time.
Btw, it *is* on GitLab also.

> Also I saw the 'porn' section on the zeronet index. I do not consider this a serious project

By ZeroNet index, I'm guessing you mean ZeroSites? Btw, all the sites on there are user-added, not official, so of course there is going to be porn, duh! Furthermore, ZeroNet is actively developed by many people, whether that be through improving the client or protocol, etc., or through making zites. Currently, we have:

* GitCenter - GitHub alternative
* ZeroMedium - Medium alternative
* ZeroMe - Twitter alternative
* ZeroTalk and ZeroVoat - BBS and Voat alternatives
* KopyKate - Video Sharing platform
* Important Zites, ZeroSites - Users add zites to these. Important Zites can also search other zites like ZeroMe, ZeroTalk, etc.
* Zirch, EulerFinder, Kaffiene - Search Engines. A client goes through some zites looking for links to add to their index.
* ZeroLSTN - Google Play Music alternative
* Thunderwave - Chat zite. Not instant, but at most 30 second delay.
* ZeroMail - Email in ZeroNet
* ZeroUp - File Streaming and Sharing
* Kiwipedia - Wikipedia alternative
* ZeroExchange - StackExchange alternative

Stuff being worked on:
* PeerMessage plugin to allow *instant* communication and broadcasting of messages throughout the network.
* IRC and Discord alternatives that utilize the PeerMessage plugin for instant chatting.
* KxoNetwork [no details released yet, still in development (by me)]

Furthermore, ZeroNet has already been blocked a couple of times by China, etc. And @nofish has fixed this a couple of times.

So, *yes*, it most certainly *is* a serious project.

**Comment by shubidubapp** [comment]
So the idea is that connected git services serves other connected git services to users right? For example if I have 1 project in the git service I have created for my team although my intention was to make 1 project available to everyone, now I have to serve other services'  projects too. Those projects can become really large files too. The worst case is yes my first intention of making our teams' projects available to everyone is succeeded but my servers bandwith is fully used all the time which means I will either need to limit the bandwith/computation used on the service or I will need a new one. I don't really think under these circumstances a project like this could become popular enough to be worth it.

**Comment by ferittuncer** [comment]
As far as I know, GitCenter suits best our needs among the alternatives. But you know much better than me so I'm glad you joined the discussion @imachug 

We would be glad if you share your thoughts about GitCenter as a decentralized alternative to GitHub. What are the advantages and disadvantages?

**Comment by cooldesigns** [comment]
@krixano Yes I mean ZeroSites. But zerosites showing in left sidebar. It must removed. 🗡

**Comment by millette** [comment]
A few more options out there:

* <https://blog.printf.net/articles/2015/05/29/announcing-gittorrent-a-decentralized-github/>
* <https://github.com/raybejjani/gitsync>

**Comment by imachug** [comment]
@ferittuncer Git Center, in fact, is a bit different from GitHub. The fact that it's decentalized makes it free. E.g. we have private repositories - you just don't publish the repo to index, but it can still be downloaded by address (address looks like BitCoin public address, but ZeroNet doesn't use blockchain in any way). This address is very big and can't be bruteforced, so it's secure. This is 1 advantage.

However, sometimes there is a problem. ZeroNet has some problems sharing sites with no peers - so it may be a bit difficult to share a repo you just created with someone else.

However, this problem is solvable - so I think Git Center can be used.

**Comment by ferittuncer** [comment]
@imachug Important part is I think identity management. What is the best practice to manage private keys/identities? I would love to hear that there is support for hardware keys.

**Comment by imachug** [comment]
Ok guys - though I don't have much time, I'll try to add more features as soon as possible, because currently Git Center sounds like a very good choice.

**Comment by vassudanagunta** [comment]
Hey all. I love the work you've been doing. Not everyone loves mine. Please read Issue 114.

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas
